### ISSUE TITLE
ImageOverlay or TileLayer with local files

### ISSUE THREAD

**Issue by rr5577** [jupyter-widgets/ipyleaflet#234]
I was trying the Velocity demo with a smaller wind dataset and would like to add a local file rasters (higher quality terrain hillshade) or a local Tilemap I created with QGIS to the map. Those files are on a different drive though, and I can´t figure out how to get them to display. It seems absolute paths don´t work even if I try it with the same file I use for the relative path:

```
# png is in the same folder as the notebook
# works
rel_url = './IPy_header.png'
io1 = ImageOverlay(url=abs_url, bounds=m.bounds)
m.add_layer(io2)

# does not work
abs_url = 'file:///E:/JUPYTER/Velocity/IPy_header.png'
io2 = ImageOverlay(url=abs_url, bounds=m.bounds)

m.add_layer(io2)
```

How can I point to a local file or a Tilemap and get it to display?

**Comment by martinRenou** [comment]
Can you try `file://localhost/E:/JUPYTER/Velocity/IPy_header.png`?

**Comment by rr5577** [comment]
that doesn´t work either unfortunately.

**Comment by martinRenou** [comment]
Also, what browser are you using? If you are using Chome/Chromium, can you try with Firefox?

**Comment by rr5577** [comment]
thanks for the javascript console tip, there´s something else indeed:
![image](https://user-images.githubusercontent.com/31547476/49787636-7b5c5280-fd27-11e8-82e7-183c7c22aaf7.png)

**Comment by rr5577** [comment]
i will ask my admin to install a different browser than chrome and try again.

**Comment by martinRenou** [comment]
Ok, so it founds the file. You're just not allowed to load it for security reasons. I guess that's because you're using Chrome. And maybe it could work on Firefox, but I'm not entirely sure.

**Comment by wouellette** [comment]
I am also having trouble, but I do not get any error flagging up in the Javascript console. The .tiff extents are highlighted in the Sidecar, but they show empty:

![image](https://user-images.githubusercontent.com/20474036/56059321-1a3f9c80-5d64-11e9-9b25-4c33a7c20e21.png)

Any clue what could be the problem?
Thanks!

**Comment by martinRenou** [comment]
I think LeafletJS only support PNG and JPG image files. I guess you would need to convert your images first. You can do that programmatically on linux https://askubuntu.com/a/60410

**Comment by wouellette** [comment]
The conversion to .png or .jpg does not seem to make any difference. The tiles are still showing blank.
That said, the tiles are rendered and colored when opening them outside of LeafletJS, like the following example:

![image](https://user-images.githubusercontent.com/20474036/56100666-ec04bd00-5f1b-11e9-9f9b-9029f707528c.png)

**Comment by rbavery** [comment]
Thanks for the cool tool! I

'm also experiencing this issue. I can't see any image in Chrome and when I tested in firefox I only see a thin outline where my image should be.

![Selection_059](https://user-images.githubusercontent.com/22258697/68557357-78ac2680-03ea-11ea-8e24-7912035b8fa4.png)

I tried using `file://` and that rmoves the file not found icon in the image overlay but there is still only a thin outline

![Selection_058](https://user-images.githubusercontent.com/22258697/68557415-92e60480-03ea-11ea-8d9c-bfd5a7e59599.png)

The image is valid and I can plot it with matplotlib. I saved the image I'm plotting here with `plt.imsave("observation_count.png",true_count_c)` to test ipyleaflet.
![Selection_060](https://user-images.githubusercontent.com/22258697/68557442-a8f3c500-03ea-11ea-837f-81eed06fa271.png)

when I try jpeg instead of png, nothing appears (no thin line)

**Comment by AlexanderJuestel** [comment]
Hello, 

I have encountered the same issue. I would like to load a raster file (tiff) into ipyleaflet from my local machine. Loading a tiff (as LocalTileLayer) does not show anything. Converting the raster to png loaded the file but it is now displayed as many tiles all over the map as you can see below. 

Is there a way to load raster files properly into ipyleaflet? (@giswqs, is there a way to do it implemented in geemap? I could not find anything right now...) Alternatively, could an array be displayed in ipyleaflet? 

Thanks for your support!

![image](https://user-images.githubusercontent.com/45469915/82734282-5771ae80-9d1a-11ea-8e5f-32ae49310561.png)

**Comment by giswqs** [comment]
@AlexanderJuestel Yes, you can use [image_overlay()](https://geemap.readthedocs.io/en/latest/source/geemap.html#geemap.geemap.Map.image_overlay) with geemap to load a local png file to the map. Check out this [notebook example](https://gist.github.com/giswqs/968193eecca257472e6bb654701510f1). 

![](https://i.imgur.com/2kH6E8Z.gif)

**Comment by giswqs** [comment]
@AlexanderJuestel ipyleaflet can also do image overlay using relative file path.

![](https://i.imgur.com/9RjdYbl.png)

#550

**Comment by AlexanderJuestel** [comment]
@giswqs thanks for the quick answer. 

I tried it with pure ipyleaflet and with the geemap implementation and it works fairly well (first image).  

However, I noticed when I am using my own implementation, that the **default map gets deactivated** for some reason and that dragging does not work anymore (second image). What I am currently doing is passing an WMS Layer, extracting a certain area and save it as image file. This image file, which could also be a high res DEM for instance should then be displaced in the map for further manipulation/processing.

If you need more information for this particular problem, let me know. 

![image](https://user-images.githubusercontent.com/45469915/82735364-863f5300-9d21-11ea-967e-797bbdcbf4d0.png)

![image](https://user-images.githubusercontent.com/45469915/82735839-09ae7380-9d25-11ea-919f-fc2d6b06671f.png)

**Comment by giswqs** [comment]
Is the basemap still listed under the layer control on your second image? Did you accidentally clear all layers before adding the local image?

**Comment by AlexanderJuestel** [comment]
Hello @giswqs, 

for some reason everything works perfectly again and as expected :) 

Thanks again for the help!
Cheers 
Alex

**Comment by AlexanderJuestel** [comment]
Hello again, 

After getting used to using image overlay I encountered another issue. For some reason, my DEM (Digital Elevation Model) is upside down when shown on a map. However, hillshades covering the same area and loaded with the same function are displayed correctly. **The loaded image files have the correct orientation when loading them in a photo editor prior to loading them into the Jupyter Notebooks.** 

Below the code that I am using, images are shown below the code.

Thanks again for the help!

```ruby

# Code in Jupyter Notebook

minx = 32286000
maxx = 32328000
miny = 5620000
maxy = 5648000
extent = [minx, maxx, miny, maxy]
center = [(maxx-minx)/2+minx, (maxy-miny)/2+miny]
center
crs = 'EPSG:4647

m = gg.Map(center=center, crs = crs, zoom=10)

raster = gg.data.Raster()

dem_map = m.load_raster(path='data/DEM5_Weisweiler_EPSG4647.tif', name = 'DEM5', extent = extent, crs = crs)
m.add_layer(dem_map)

hillshade_map = m.load_raster(path='data/Hillshade5_Weisweiler.tif', name = 'Hillshade5', extent = extent, crs = crs)
m.add_layer(hillshade_map)

#################################
#Main Loading Function in Pycharm:

    def load_raster(self, **kwargs):

        url = kwargs.get('path', None)
        name = kwargs.get('name', None)
        extent = kwargs.get('extent', None)
        crs = kwargs.get('crs', 'EPSG:4326')

        if 'crs' in kwargs.keys():
            if crs is None or crs == 'EPSG:4326':
                extent_transf = extent
            else:
                proj_custom = Proj(init=crs)
                proj_deafult = Proj(init='epsg:4326')

                extent_transf = np.zeros(4)
                extent_transf[0], extent_transf[1] = transform(proj_custom, proj_deafult, extent[0],
                                                                    extent[2])
                extent_transf[2], extent_transf[3] = transform(proj_custom, proj_deafult, extent[1],
                                                 extent[3])
        else:
            extent_transf = extent

        raster = data.Raster()

        array = raster.load_raster(path = url)

        array = np.flipud(array)

        map = Image.fromarray(array)
        map = map.convert('L')
        map.save('%s.png' % name)

        image = ipyleaflet.ImageOverlay(url='%s.png' % name, name=name, bounds=((extent_transf[1], extent_transf[0]), (extent_transf[3], extent_transf[2])))

        return image
```

Upside down DEM. 
![Ashampoo_Snap_2020 05 26_14h29m31s_012_](https://user-images.githubusercontent.com/45469915/82901218-efaba580-9f5d-11ea-9275-f51b0827ac50.png)

Correct Hillshades.
![Ashampoo_Snap_2020 05 26_14h25m49s_011_](https://user-images.githubusercontent.com/45469915/82901222-f1756900-9f5d-11ea-8cec-ac7188f32fdb.png)

**Comment by martinRenou** [comment]
The discussion is drifting away from the original purpose of the issue.

Maybe you could open another issue or ask your question on another channel?

**Comment by sunny-g** [comment]
I'm still having this issue. If I use a relative local path, I don't get any errors in the console, but get a blank image outline like in https://github.com/jupyter-widgets/ipyleaflet/issues/234#issuecomment-552272122. If I spawn a local file server `python -m http.server 8000`, I get the same result in the map and the local file server reports this:

```
127.0.0.1 - - [20/Jan/2021 22:12:34] "GET /swiftera-imagery/TUS13/20210107T153729Z_2787_POM1_ST2_2_P.tif HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41940)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3.8/http/server.py", line 654, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.8/http/server.py", line 853, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.8/shutil.py", line 205, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
```

**Comment by banesullivan** [comment]
Thought I'd chime in and give a plug for something I developed to solve the issue of viewing local raster files with ipyleaflet: https://github.com/banesullivan/flask-tileserver#ipyleaflet-tile-layers

In essence, it's a little package that will launch a local tile server in a background thread for use with ipyleaflet. Check out the README for an example, (the code here is subject to change):

```py
from tileserver import get_leaflet_tile_layer
from ipyleaflet import Map, projections, ScaleControl, FullScreenControl, SplitMapControl

m = Map(
        center=(37.7249511580583, -122.27230466902257),
        zoom=9, crs=projections.EPSG3857,
       )

# Create two tile layers from 2 seperate raster files
l = get_leaflet_tile_layer('~/Desktop/TC_NG_SFBay_US_Geo.tif',
                           band=1, palette='matplotlib.Viridis_20', vmin=50, vmax=200)
r = get_leaflet_tile_layer('~/Desktop/small.tif',
                           band=2, palette='matplotlib.Plasma_6', vmin=0, vmax=150)

control = SplitMapControl(left_layer=l, right_layer=r)
m.add_control(control)

m.add_control(ScaleControl(position='bottomleft'))
m.add_control(FullScreenControl())
m
```

![ipyleaflet](https://user-images.githubusercontent.com/22067021/142741793-b16ab680-5a78-47cf-ae01-4365e8665272.gif)
