### ISSUE TITLE
Support for PyPy3.6

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#300]
I'm playing with PyPy 7 and Python 3.6 (alpha), see https://pypy.org/download.html, and to my great excitement I can pip-install ipywidgets out of the box! But if I try installing ipyleaflet it stumbled when attempting to install pandas, see below. Is that really required for ipyleaflet? Could it be made optional maybe?

I did some more tests and found that the `rastersio`, `matplotlib` and `geopandas` requirements are the tricky ones. A former version of Pandas and Pypy might have worked together according to https://morepypy.blogspot.com/2017/10/pypy-v59-released-now-supports-pandas.html...

Of course, running Jupyter on PyPy doesn't seem to work (yet), but running ipyleaflet might still be useful inside test suites. Need to stop here, but I'm baffled how much is working now on PyPy... Even `scipy` did compile (afer some minutes), but I had no more time to test much...

```
$ bin/pip3 install ipyleaflet
Collecting ipyleaflet
  Using cached https://files.pythonhosted.org/packages/2f/7f/f60b723fcc8250fcd64a9b9b70b4049cfa06b6cd412a65511facbeedb889/ipyleaflet-0.9.2-py2.py3-none-any.whl
Requirement already satisfied: ipywidgets<8,>=7.0.0 in ./site-packages (from ipyleaflet) (7.4.2)
Collecting traittypes<3,>=0.2.1 (from ipyleaflet)
  Using cached https://files.pythonhosted.org/packages/9c/d1/8d5bd662703cc1764d986f6908a608777305946fa634d34c470cd4a1e729/traittypes-0.2.1-py2.py3-none-any.whl
Collecting xarray<0.10.8,>=0.10 (from ipyleaflet)
  Using cached https://files.pythonhosted.org/packages/03/8a/08a996f9552c65ad955977d7a13fc3c423a90ca457373c3cb7caafb67b97/xarray-0.10.7-py2.py3-none-any.whl
Collecting branca<0.4,>=0.3.1 (from ipyleaflet)
  Using cached https://files.pythonhosted.org/packages/63/36/1c93318e9653f4e414a2e0c3b98fc898b4970e939afeedeee6075dd3b703/branca-0.3.1-py3-none-any.whl
Requirement already satisfied: ipykernel>=4.5.1 in ./site-packages (from ipywidgets<8,>=7.0.0->ipyleaflet) (5.1.0)
Requirement already satisfied: traitlets>=4.3.1 in ./site-packages (from ipywidgets<8,>=7.0.0->ipyleaflet) (4.3.2)
Requirement already satisfied: nbformat>=4.2.0 in ./site-packages (from ipywidgets<8,>=7.0.0->ipyleaflet) (4.4.0)
Requirement already satisfied: widgetsnbextension~=3.4.0 in ./site-packages (from ipywidgets<8,>=7.0.0->ipyleaflet) (3.4.2)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in ./site-packages (from ipywidgets<8,>=7.0.0->ipyleaflet) (7.3.0)
Collecting numpy>=1.11 (from xarray<0.10.8,>=0.10->ipyleaflet)
  Using cached https://files.pythonhosted.org/packages/cf/8d/6345b4f32b37945fedc1e027e83970005fc9c699068d2f566b82826515f2/numpy-1.16.2.zip
Collecting pandas>=0.18.0 (from xarray<0.10.8,>=0.10->ipyleaflet)
  Using cached https://files.pythonhosted.org/packages/81/fd/b1f17f7dc914047cd1df9d6813b944ee446973baafe8106e4458bfb68884/pandas-0.24.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vx/4_flzs5x2tvdhdtdm0ynz6bxgmj9tg/T/pip-install-7vg803zd/pandas/setup.py", line 438, in <module>
        if python_target < '10.9' and current_system >= '10.9':
      File "/Users/gherman/Downloads/pypy3.6-v7.0.0-osx64/lib-python/3/distutils/version.py", line 52, in __lt__
        c = self._cmp(other)
      File "/Users/gherman/Downloads/pypy3.6-v7.0.0-osx64/lib-python/3/distutils/version.py", line 335, in _cmp
        if self.version == other.version:
    AttributeError: 'LooseVersion' object has no attribute 'version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vx/4_flzs5x2tvdhdtdm0ynz6bxgmj9tg/T/pip-install-7vg803zd/pandas/
```

**Comment by SylvainCorlay** [comment]
Hey @deeplook thanks for posting here. Pandas is a second-order dependency pulled by xarray. There are some debates on whether xarray shouls be a string dependency. Removing it would require some work in the velocity layer. Nothing else depends on it.

**Comment by bhy** [comment]
A workaround is to install `pandas` with:

`MACOSX_DEPLOYMENT_TARGET=10.9 pip install pandas`
