### ISSUE TITLE
ImportError: cannot import name 'Map' from 'ipyleaflet'

### ISSUE THREAD

**Issue by Juanlu001** [jupyter-widgets/ipyleaflet#375]
```
(py37) juanlu@centauri ~ $ pip list | grep ipyleaflet
ipyleaflet                    0.10.3
(py37) juanlu@centauri ~ $ python -c "from ipyleaflet import Map"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Map' from 'ipyleaflet' (/home/juanlu/.miniconda36/envs/py37/lib/python3.7/site-packages/ipyleaflet/__init__.py)
(py37) juanlu@centauri ~ $ python -c "from ipyleaflet.leaflet import Map"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/juanlu/.miniconda36/envs/py37/lib/python3.7/site-packages/ipyleaflet/leaflet.py", line 21, in <module>
    from geopandas import GeoDataFrame
ModuleNotFoundError: No module named 'geopandas'
```

Looking at the metadata of the wheel:

```
Requires-Dist: branca (<0.4geopandas>=0.5.0,>=0.3.1)
```

**Comment by martinRenou** [comment]
Thanks a lot for fixing this @Juanlu001

**Comment by martinRenou** [comment]
I just made a 0.10.4 release with your fix. The conda package should be updated soon.

**Comment by Juanlu001** [comment]
Thanks to you for the quick response!
