### ISSUE TITLE
0.16.0: sphinx is failing

### ISSUE THREAD

**Issue by kloczek** [jupyter-widgets/ipyleaflet#986]
Looks like on generate documetation sphins shows some warnings and crashes with call stack

Here is pytest output:
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 46 added, 0 changed, 0 removed
executing draw_control4%] controls/draw_control
executing fullscreen_controlntrols/fullscreen_control
executing layers_control] controls/layers_control
executing legend_control] controls/legend_control
executing measure_control controls/measure_control
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.Marker:72: WARNING: duplicate object description of ipyleaflet.leaflet.Marker.opacity, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear_circle_markers:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear_circle_markers, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear_circles:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear_circles, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear_markers:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear_markers, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear_polygons:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear_polygons, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear_polylines:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear_polylines, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.clear_rectangles:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.clear_rectangles, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.DrawControl.on_draw:1: WARNING: duplicate object description of ipyleaflet.leaflet.DrawControl.on_draw, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.FullScreenControl:1: WARNING: duplicate object description of ipyleaflet.leaflet.FullScreenControl, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.LayersControl:1: WARNING: duplicate object description of ipyleaflet.leaflet.LayersControl, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.LegendControl:1: WARNING: duplicate object description of ipyleaflet.leaflet.LegendControl, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.LegendControl:5: WARNING: duplicate object description of ipyleaflet.leaflet.LegendControl.title, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.LegendControl:11: WARNING: duplicate object description of ipyleaflet.leaflet.LegendControl.legend, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.LegendControl.add_legend_element:1: WARNING: duplicate object description of ipyleaflet.leaflet.LegendControl.add_legend_element, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.LegendControl.remove_legend_element:1: WARNING: duplicate object description of ipyleaflet.leaflet.LegendControl.remove_legend_element, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:1: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:5: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.primary_length_unit, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:11: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.secondary_length_unit, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:17: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.primary_area_unit, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:23: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.secondary_area_unit, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:29: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.active_color, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl:35: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.completed_color, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl.add_area_unit:1: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.add_area_unit, other instance in api_reference/index, use :noindex: for one of them
/usr/lib/python3.8/site-packages/ipyleaflet/leaflet.py:docstring of ipyleaflet.leaflet.MeasureControl.add_length_unit:1: WARNING: duplicate object description of ipyleaflet.leaflet.MeasureControl.add_length_unit, other instance in api_reference/index, use :noindex: for one of them

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 79, in apply_transforms
    super().apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.8/site-packages/jupyter_sphinx/execute.py", line 170, in apply
    raise ExtensionError(
sphinx.errors.ExtensionError: Cell raised uncaught exception:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /usr/lib/python3.8/site-packages/xyzservices/lib.py:42, in Bunch.__getattr__(self, key)
     41 try:
---> 42     return self.__getitem__(key)
     43 except KeyError:

KeyError: 'Hydda'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 3>()
      1 from ipyleaflet import Map, MeasureControl, basemaps
----> 3 m = Map(center=(43.0327, 6.0232), zoom=9, basemap=basemaps.Hydda.Full)
      5 measure = MeasureControl(
      6     position='bottomleft',
      7     active_color = 'orange',
      8     primary_length_unit = 'kilometers'
      9 )
     10 m.add_control(measure)

File /usr/lib/python3.8/site-packages/xyzservices/lib.py:44, in Bunch.__getattr__(self, key)
     42     return self.__getitem__(key)
     43 except KeyError:
---> 44     raise AttributeError(key)

AttributeError: Hydda

Extension error:
Cell raised uncaught exception:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /usr/lib/python3.8/site-packages/xyzservices/lib.py:42, in Bunch.__getattr__(self, key)
     41 try:
---> 42     return self.__getitem__(key)
     43 except KeyError:

KeyError: 'Hydda'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 3>()
      1 from ipyleaflet import Map, MeasureControl, basemaps
----> 3 m = Map(center=(43.0327, 6.0232), zoom=9, basemap=basemaps.Hydda.Full)
      5 measure = MeasureControl(
      6     position='bottomleft',
      7     active_color = 'orange',
      8     primary_length_unit = 'kilometers'
      9 )
     10 m.add_control(measure)

File /usr/lib/python3.8/site-packages/xyzservices/lib.py:44, in Bunch.__getattr__(self, key)
     42     return self.__getitem__(key)
     43 except KeyError:
---> 44     raise AttributeError(key)

AttributeError: Hydda
```
</details>

**Comment by jasongrout** [comment]
Looks like this has been fixed now. Thanks for raising the issue.
